freebsd_instance:
  image_family: freebsd-13-0

task:
  
  env:
    AUTOMATED_TESTING: 1
    PERL_MOD_DIR: /perl5
    #MAKEFLAGS: -j4

  cpan_cache:
    folder: /perl5
    reupload_on_changes: false # set to false if there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS 20220321a
      
  install_script:
    #- sudo pkg install -y llvm  #  need recent version for PDL
    - echo $SHELL
    - cc -v
    - sudo pkg install -y autoconf automake libtool pkgconf sqlite3 gmake git cmake
    - sudo pkg install -y p5-App-cpanminus
    
    - sudo cpanm local::lib
    #- cpanm --local-lib=$PERL_MOD_DIR local::lib && eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - echo probe local::lib
    - perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib
    - echo Run it anyway...
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)

    - cpanm PDL

    # get deps from cpanfile
    - cpanm --notest --installdeps .
    
    - cpanm --installdeps --notest Alien::geos::af
    #- export ALIEN_GEOS_ENABLE_TESTS=1
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-geos.git
    #- MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-geos.git
    #- find `perl -MAlien::geos::af -E'say Alien::geos::af->dist_dir'` -print
    #- echo GEOS_libs
    #- perl -MAlien::geos::af -E'say "Version: " . Alien::geos::af->version'
    - perl -MAlien::geos::af -E'say join "\n", Alien::geos::af->dynamic_libs'
    - perl -MAlien::geos::af -E'say system "objdump -x $_" for Alien::geos::af->dynamic_libs' | grep NEEDED | sort -u
    - echo XXXX
    - echo GEOS CONFIG 
    - cat `perl -MAlien::geos::af -E'print Alien::geos::af->bin_dir . "/geos-config"'`
    - echo XXXX
    - echo GEOS cflags
    - export gconfloc=`perl -MAlien::geos::af -E'print Alien::geos::af->dist_dir . "/bin/geos-config"'`
    - echo `${gconfloc} --cflags`

    #- cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
    - cpanm --installdeps --notest Alien::libtiff
    - MAKEFLAGS=-j4 cpanm -v Alien::libtiff

    - export LD_LIBRARY_PATH=`perl -MAlien::libtiff -E'print Alien::libtiff->dist_dir . q{/lib}'`:${LD_LIBRARY_PATH}
    - echo LD_LIBRARY_PATH is ${LD_LIBRARY_PATH}
    - cpanm --installdeps --notest -v Alien::proj
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-proj.git
    - find `perl -MAlien::proj -E'say Alien::proj->dist_dir'` -print

    - export LD_LIBRARY_PATH=`perl -MAlien::geos::af -E'print Alien::geos::af->dist_dir . q{/lib}'`:${LD_LIBRARY_PATH}
    - echo LD_LIBRARY_PATH is ${LD_LIBRARY_PATH}
    - cpanm --installdeps --notest Alien::gdal
    #- export LDFLAGS=`perl -MAlien::geos::af -E'print q{-L}, Alien::geos::af->dist_dir, q{/lib}'`
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git

    - cpanm --notest --installdeps Geo::GDAL::FFI

    - echo 'GDAL libs' 
    - perl -MAlien::gdal -E'say join "\n", Alien::gdal->dynamic_libs'
    - perl -MAlien::gdal -E'say system "objdump -x $_" for Alien::gdal->dynamic_libs' | grep NEEDED | sort -u

    - echo GDAL LDD
    - ldd `perl -MAlien::gdal -E'print q{}, Alien::gdal->dist_dir, q{/lib/libgdal.so}'`
    - perl -MAlien::gdal -E'say Alien::gdal->run_utility ("gdalwarp", "--version")'

  script:
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - echo LD_LIBRARY_PATH is ${LD_LIBRARY_PATH}
    #- export LD_LIBRARY_PATH=`perl -MAlien::geos::af -E'print Alien::geos::af->dist_dir . q{/lib}'`
    #- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`perl -MAlien::proj -E'print Alien::proj->dist_dir . q{/lib}'`
    #- export LDFLAGS=`perl -MAlien::geos::af -E'print q{-L}, Alien::geos::af->dist_dir, q{/lib}'`
    - echo LD_LIBRARY_PATH is now ${LD_LIBRARY_PATH}
    - cpanm --verbose --reinstall Geo::GDAL::FFI
    