freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  
  env:
    AUTOMATED_TESTING: 1
    PERL_MOD_DIR: /perl5
    #MAKEFLAGS: -j4

  cpan_cache:
    folder: /perl5
    reupload_on_changes: false # set to false if there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS 20200530
      
  install_script:
    - sudo pkg install -y autoconf automake libtool pkgconf sqlite3 gmake git
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm local::lib
    #- cpanm --local-lib=$PERL_MOD_DIR local::lib && eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - echo probe local::lib
    - perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib
    - echo Run it anyway...
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    #- cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
    - cpanm --installdeps --notest -v Alien::proj
    #- export WD=`pwd`
    #- git co https://github.com/shawnlaffan/perl-alien-proj.git
    #- cd perl-alien-proj && perl Makefile.PL && gmake install && cd -
    #- cd $WD
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-proj.git
    - cpanm --installdeps --notest Alien::libtiff
    - MAKEFLAGS=-j4 cpanm -v Alien::libtiff
    - MAKEFLAGS=-j4 cpanm -v Alien::geos::af
    - cpanm --installdeps --notest Alien::gdal
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git
    - cpanm --notest FFI::Platypus
    - cpanm --notest PDL
    - cpanm --notest --installdeps Geo::GDAL::FFI

  script:
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - cpanm --verbose --reinstall Geo::GDAL::FFI
    