freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  
  env:
    AUTOMATED_TESTING: 1
    PERL_MOD_DIR: /perl5
    #MAKEFLAGS: -j4

  cpan_cache:
    folder: /perl5
    reupload_on_changes: false # set to false if there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS 20210115
      
  install_script:
    - sudo pkg install -y autoconf automake libtool pkgconf sqlite3 gmake git cmake
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm local::lib
    #- cpanm --local-lib=$PERL_MOD_DIR local::lib && eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - echo probe local::lib
    - perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib
    - echo Run it anyway...
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)

    # get deps from cpanfile
    - cpanm --notest --installdeps .
    
    #- cpanm --local-lib=~/perl_modules local::lib && eval $(perl -I ~/perl_modules/lib/perl5/ -Mlocal::lib)
    - cpanm --installdeps --notest Alien::libtiff
    - MAKEFLAGS=-j4 cpanm -v Alien::libtiff

    - cpanm --installdeps --notest -v Alien::proj
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-proj.git
    - find `perl -MAlien::proj -E'say Alien::proj->dist_dir'` -print

    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-geos.git@cmake
    - find `perl -MAlien::geos::af -E'say Alien::geos::af->dist_dir'` -print

    - cpanm --installdeps --notest Alien::gdal
    - MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git

    - cpanm --notest --installdeps Geo::GDAL::FFI
    
    - perl -MAlien::gdal -E'say join "\n", Alien::gdal->dynamic_libs'
    - perl -MAlien::gdal -E'say system "objdump -x $_" for Alien::gdal->dynamic_libs' | grep NEEDED | sort -u

  script:
    - eval $(perl -I ${PERL_MOD_DIR}/lib/perl5/ -Mlocal::lib)
    - cpanm --verbose --reinstall Geo::GDAL::FFI
    