branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry
  #- .alienbuild\plugin_fetch_cache

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.38.2.2
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  - cpanm --installdeps --notest Alien::sqlite
  - cpanm -v --notest Alien::sqlite
  - cpanm --installdeps --notest Alien::geos::af
  - cpanm -v Alien::geos::af
  - cpanm --installdeps --notest Alien::sqlite
  - cpanm -v Alien::sqlite
  - cpanm --installdeps --notest Alien::libtiff
  - cpanm -v Alien::libtiff
  - cpanm --notest --installdeps Alien::proj
  - cpanm -v Alien::proj
  #- cpanm --verbose Alien::automake
  - cpanm --installdeps --notest Alien::gdal
  - cpanm -v Alien::gdal
  #  get rest of deps from cpanfile  
  - cpanm --installdeps --notest .
  
  #- cpanm --quiet --notest --installdeps .
  - cpanm --quiet --notest Alien::Build::Plugin::Fetch::Cache


build_script:
  - prove
  - cpanm --reinstall --verbose Geo::GDAL::FFI
  - echo 1

