branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry
  - .alienbuild\plugin_fetch_cache

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  
  #  get deps from cpanfile  
  - cpanm --installdeps --notest .

  - cpanm -v --notest Alien::sqlite
  - cpanm -installdeps --notest Alien::geos::af
  - cpanm -v git://github.com/shawnlaffan/perl-alien-geos.git@revised_geos_config
  - cpanm -v --notest Alien::sqlite
  - cpanm -v --notest Alien::sqlite
  - cpanm -v --notest Alien::libtiff
  - cpanm --notest --installdeps Alien::proj
  - cpanm -v --notest Alien::proj
  #- cpanm --notest --installdeps git://github.com/shawnlaffan/perl-alien-proj.git
  #- cpanm -v git://github.com/shawnlaffan/perl-alien-proj.git
  #- cpanm -v --notest git://github.com/shawnlaffan/perl-alien-gdal.git
  - cpanm -v --notest Alien::gdal
  
  #- cpanm --quiet --notest --installdeps .
  - cpanm --quiet --notest Alien::Build::Plugin::Fetch::Cache


build_script:
  - cpanm --reinstall --verbose Geo::GDAL::FFI
  - echo 1

