name: linux_default_locale

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL_MOD_DIR: /home/runner/perl5/lib/perl5

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: cmake for geos
        run: |
          sudo apt-get --yes install cmake

      - name: Locale check
        run: |
          locale -a
          echo Current locale:
          locale

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo '20210911' >> perlversion.txt
          ls -l perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install Dynamic Dependencies
        run: |
          which -a cpanm
          which -a perl
          cpanm --notest local::lib
          echo $(perl -Mlocal::lib=${HOME}/perl5)
          eval "$(perl -Mlocal::lib=${HOME}/perl5)"
          cpanm --notest Alien::Build  
          cpanm --installdeps --notest Alien::sqlite
          cpanm -v Alien::sqlite
          cpanm --installdeps --notest Alien::libtiff
          cpanm -v Alien::libtiff
          cpanm --installdeps --notest Alien::geos::af
          cpanm -v git://github.com/shawnlaffan/perl-alien-geos.git@revised_geos_config
          cpanm --installdeps --notest Alien::proj
          cpanm -v Alien::proj
          cpanm --installdeps --notest Alien::gdal
          MAKEFLAGS=-j4 cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git
          #cpanm -v Alien::gdal
          
      - name: Install Geo::GDAL::FFI deps
        run: |
          cpanm --installdeps Geo::GDAL::FFI
  
      - name: Build
        run: |
          cpanm --reinstall --verbose Geo::GDAL::FFI
