name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: c:\cx\lib\perl5
  PERL_LOCAL_LIB_ROOT: c:/cx
  PERL_MB_OPT: --install_base C:/cx
  PERL_MM_OPT: INSTALL_BASE=C:/cx
  ALIEN_BUILD_PRELOAD: Fetch::Cache
  AUTOMATED_TESTING: 1

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  
      - name: perl -V
        run: perl -V
        
      - name: Prepare for CPAN cache
        run: |
          perl -V > perlversion.txt
          echo '20220321' >> perlversion.txt
          dir perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: c:\cx
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Prepare for Alien cache
        run: |
          perl -V > aliencache.txt
          echo 'aliens 20201210' >> aliencache.txt
          dir aliencache.txt

      - name: Cache Alien downloads
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\.alienbuild
          key: ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}
  
      - name: Install dependencies 1
        run: |
          # cpanm --notest PDL
          #  get deps from cpanfile
          cpanm --notest --installdeps .

      - name: Install dependencies Alien::MSYS
        run: |
          cpanm --notest Alien::MSYS

      - name: Install dependencies Alien::sqlite
        run: |
          cpanm --notest --installdeps Alien::sqlite
          cpanm https://github.com/shawnlaffan/perl-alien-sqlite.git
      
      - name: Install dependencies Alien::libtiff
        run: |
          cpanm -v --notest Alien::libtiff

      - name: Install dependencies Alien::proj
        run: |
          cpanm --notest --installdeps Alien::proj
          cpanm -v https://github.com/shawnlaffan/perl-alien-proj.git

      - name: Install dependencies Alien::geos::af
        run: |
          cpanm --notest --installdeps Alien::geos::af          
          cpanm -v https://github.com/shawnlaffan/perl-alien-geos.git

      - name: Install dependencies for Alien::gdal
        run: |
          cpanm --notest --installdeps Alien::gdal
          perl -MAlien::geos::af -E"say Alien::geos::af->version"
          cpanm -v https://github.com/shawnlaffan/perl-alien-gdal.git
      
      - name: Install Geo::GDAL::FFI deps
        run: |
          cpanm --installdeps Geo::GDAL::FFI
  
      - name: Build
        run: |
          cpanm --reinstall --verbose Geo::GDAL::FFI

      #- name: Zip _alien
      #  #if: ${{ failure() }}
      #  if: ${{ always() }}
      #  run: |
      #    pwd
      #    & 7z.exe a _alien.7z _alien
      #    
      #- name: Upload artefact
      #  if: ${{ always() }}
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: _alien.7z
      #    path: ./_alien.7z
